version: '3.8'

services: 
    mysqldb:
        image: mysql
        restart: always
        env_file: ./.env
        environment:
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_NAME
        ports:
        - $PORT:$PORT
        volumes: 
        - db-config:/etc/mysql
        - db-data:/var/lib/mysql
        - ./db/backup/files/:/data_backup/data

    app:
        build:
          context: .
          dockerfile: ./app/Dockerfile
        image: vehicle-rental
        depends_on:
          - mysqldb
        stdin_open: true
        tty: true
    
    